### ISSUE TITLE
Optional "not found" error

### ISSUE THREAD

**Issue by drj-io** [deebloo/find-and-replace#1]
Nice module, though it would be nice if the error throwing were optional.

**Comment by deebloo** [comment]
Thanks! And yes you are probably correct. I'll look j to it.

**Comment by deebloo** [comment]
@drj-io I was thinking about what you had said and as I tweaked it made sense to change the interface. It is in master now if you want to take a look and the master readme has the updated api. Let me know what you think. I think it is cleaner and will be more extensible down the line.

You can add multiple complete or error methods if you so choose.

**Comment by deebloo** [comment]
@drj-io I am going to close this issue unless you have any feedback based on the latest changes.
