### ISSUE TITLE
Finding and Replacing in multiple files

### ISSUE THREAD

**Issue by iamdangavin** [deebloo/find-and-replace#2]
I am pretty new to node and I am running `find-and-replace` and it works great when I want to find variables in just one file. Can't seem to get it working for multiple files.

Was thinking I could just run it like this:

```
    find = require("find-and-replace");

    find.src('./app/scss/screen.scss')
        .dest('./app/scss/screen.scss')
        .replace({
            "'{{adWidthpx}}'": dimensions.width + 'px',
            "'{{adHeightpx}}'": dimensions.height + 'px'
        })
        .complete(function () {
            console.log("Replaced variables in screen.scss")
        })
        .error(function (err) {
            console.log(err);
        });

    find.src('./package/index.html')
        .dest('./package/index.html')
        .replace({
            "{{adTitle}}": title,
            "{{adWidth}}": dimensions.width,
            "{{adHeight}}": dimensions.height,
        })
        .complete(function () {
            console.log("Replaced variables in index.html");
        })
        .error(function (err) {
            console.log(err);
        });
```

But it will only find and replace for the second call for find and replace. Is this not something that can happen or am I just missing something simple...

**Comment by deebloo** [comment]
let me look into it. that very well may be a bug.

**Comment by deebloo** [comment]
@iamdangavin yup totally a bug. Ill look into it and try to push a fix out. may require a slight api change. ill update the task when complete.

**Comment by deebloo** [comment]
@iamdangavin should be good. when you get a chance update to the newest version 1.0.2 and see if that fixes it for you. if so ill close this issue

**Comment by iamdangavin** [comment]
@deebloo worked like a charm. Thanks!

**Comment by deebloo** [comment]
@iamdangavin my pleasure :)
